[tools]
actionlint = "1.7.12"
gitleaks = "8.30.1"
hk = "1.45.0"
just = "1.50.0"
bun = "1.3.13"
prettier = "3.8.3"
pkl = "0.31.1"
osv-scanner = "2.3.8"
trivy = "0.70.0"
pipx = "1.12.0"
semgrep = "1.162.0"
