[tools]
actionlint = "1.7.12"
gitleaks = "8.30.1"
hk = "1.58.1"
just = "1.58.0"
bun = "1.4.2"
prettier = "3.9.6"
pkl = "0.32.1"
osv-scanner = "2.5.1"
trivy = "0.74.0"
pipx = "1.17.2"
semgrep = "1.177.0"
